"""add linked tag fields

Revision ID: 766e49445773
Revises: 2e6d86e2974f
Create Date: 2016-07-22 12:45:49.038921

"""

# revision identifiers, used by Alembic.
revision = '766e49445773'
down_revision = '2e6d86e2974f'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_tag', sa.Column('linked', sa.Boolean(), nullable=True))
    op.add_column('address_tag', sa.Column('linked_address', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_tag', 'linked_address')
    op.drop_column('address_tag', 'linked')
    ### end Alembic commands ###
